# Generated by Django 5.1.2 on 2024-11-12 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
