# Generated by Django 5.1.2 on 2024-11-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_paid_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=None, editable=False, max_length=20, unique=True),
        ),
    ]
